### ISSUE TITLE
Improve usability from Java only projects

### ISSUE THREAD

**Issue by 05nelsonm** [05nelsonm/kmp-tor#94]
- [x] Remove public usage of inline classes
- [x] Create Java coroutine wrapper extension module
- [ ] Create Java Javafx sample
- [x] Create Java Android sample
